---
kind: pkgfile.Build
spec:
  targets:
    - sbc-mixtile-blade3
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - TOOLS_PREFIX
    - TOOLS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.14.0-37-g6c312e4
      - name: TOOLS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: TOOLS
        defaultValue: v1.14.0-8-g9776960
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
